version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-laravel-app
    container_name: my-laravel-container
    working_dir: /var/www/html
    ports:
      - "8080:9000"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
      - DB_HOST=mysql
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: my-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: laravel-cart
    ports:
      - "3307:3306"
